# Server
server.port=8080

# SQLite Datasource
spring.datasource.url=jdbc:sqlite:tbe.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Basic Auth (default credentials)
tbe.auth.username=tbe
tbe.auth.password={noop}trustn00ne

# Jackson
spring.jackson.default-property-inclusion=non_null
