services:
  backend:
    cpus: 1.2
    mem_limit: 150m    
    image: nello-jj-api:latest
    # Ports 6502 is not exposed outside the compose friends
    build:
      context: ./backend
    volumes:
      # Bind a single file
      - type: bind        
        source: $NELLO_HOME/nello.db
        target: /app/nello/nello.db
    # TODO: Configure at will
    environment:
      - NELLO_JWT_EXPIRATION_HOURS=7
      - NELLO_JWT_SECRET=nello-prod
  frontend:
    cpus: 0.50
    mem_limit: 8m
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nello-jj-fe:latest
    ports:
      # Port to be in sync with external routing
      - "$NELLO_PROXY_PORT:80"
    depends_on:
      - backend
  backup:
    cpus: 0.10
    mem_limit: 6m
    build:
      context: ./backup-gurl
    volumes:
      - type: bind
        source: $NELLO_HOME
        target: /app/nello     
    depends_on:
      - backend
      - frontend 